version: "3.9"
services:
  postfix:
    container_name: postfix
    build: postfix/
    hostname: ${DOMAIN}
    dns: 127.0.0.1
    tty: true
    extra_hosts:
      - ${DOMAIN}:127.0.0.1
    ports:
      - "25:25"
      - "110:110"
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server --console-address "0.0.0.0:9001" --address "0.0.0.0:9000" /data
  file_storage_api:
    build: ./file_storage_api
    ports:
      - "3200:3200"
    depends_on:
      - minio
  parsing:
    build: ./parsing
    ports:
      - "3201:3201"
    depends_on:
      - file_storage_api

volumes:
  minio_storage: {}