version: "3.9"
services:
  postfix:
    container_name: postfix
    build: postfix/
    hostname: ${DOMAIN}
    dns: 8.8.8.8
    tty: true
    extra_hosts:
      - ${DOMAIN}:0.0.0.0
    ports:
      - "587:25"
      - "110:110"
    volumes:
      - /etc/letsencrypt/archive/${DOMAIN}:/etc/letsencrypt/live/${DOMAIN}
  minio:
    container_name: minio
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server --console-address "0.0.0.0:9001" --address "0.0.0.0:9000" /data
  filestorageapi:
    container_name: filestorageapi
    build: ./filestorageapi
    ports:
      - "3200:3200"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    depends_on:
      - minio
  parsing:
    container_name: parsing
    build: ./parsing
    ports:
      - "3201:3201"
    depends_on:
      - filestorageapi
    environment:
      DOMAIN: ${DOMAIN}
  archive-cli:
    container_name: archive-cli
    build: ./archive-cli
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      DELAY: "5d"
    profiles:
      - do_not_up
    depends_on:
      - minio
volumes:
  minio_storage: {}